config/routes.rb
AgentSignals::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
    get "logout",     to: "devise/sessions#destroy",    as: "logout"
    get "login",      to: "devise/sessions#new",        as: "login"
    get "signup",     to: "devise/registrations#new",   as: "signup"
  end

  get 'searches/show'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get "contact_form/new"
  get "contact_form/create"

  resources :users
  get "dashboard",  to: "users#dashboard"

  get "web_to_lead" => "leads#new_web_lead", as: "web_to_lead"
  put "create_web_lead" => "leads#create_web_lead", as: "create_web_lead"
  put "generate" => "leads#external_form"

  get 'contact_us' => 'contact_forms#new', as: 'contact_us'
  get 'pricing' => 'pages#pricing', as: 'pricing'

  # Wizards
  resources :after_signup

  resources :agents
  resources :listings
  resources :offers
  resources :opportunities
  resources :tasks
  resources :calendar
  resources :events do
    get :new_task,          on: :collection
    get :new_appointment,   on: :collection
    get :new_showing,       on: :collection
  end

  resources :users do 
    get :settings, on: :member
  end
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      post :convert_to_client
      get :convert
    end
  end

  resources :clients

  namespace :admin do
    resources :users
    resources :organizations
  end

  resources :contact_forms

  resources :contacts
  resources :accounts do
    member do
      get :settings
      post :add_user
    end
  end


end

app/models/listing.rb
# t.string   "title"
# t.decimal  "price",        precision: 10, scale: 0
# t.integer  "house_number"
# t.string   "street_name"
# t.string   "city_name"
# t.string   "zipcode"
# t.datetime "created_at"
# t.datetime "updated_at"
# t.string   "listing_number"
# t.string   "listing_owner"

class Listing < ActiveRecord::Base
  validates_presence_of :title, :price, :street_name, :city_name, :house_number,
                        :zipcode, :listing_number, :listing_owner

  belongs_to :account
  belongs_to :agent

  has_many :client_listings, foreign_key: :user_id
  has_many :clients, through: :client_listings, source: :client

  geocoded_by :listing_full_address
  after_validation :geocode

  # include Tire::Model::Search
  # include Tire::Model::Callbacks

  scope :viewable_on_map, -> { where.not(latitude: nil) }

  def street_address
    if house_number && street_name
      house_number.to_s +  ' ' + street_name
    end
  end

  def listing_full_address
    if street_address && city_name && state && zipcode
      street_address + ', ' + city_name + ' ' + state + ', ' +  zipcode
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    if params[:query]
      @listings = Listing.tire.search params[:query]
    else
      @listings = current_user.account.listings
    end
    if @listings
      @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
        marker.lat listing.latitude
        marker.lng listing.longitude
        marker.infowindow listing.description
        marker.json({ title: listing.title })
        marker.picture({
          "url" => "mapicons/house.png",
          "width" => 32,
          "height" => 32
          })
      end
    end
  end

  def new
    @listing = current_user.account.listings.new
    @account_contacts = current_user.account.contacts.map(&:full_name)
    @account_users    = current_user.account.users.map(&:full_name)
  end

  def create
    @listing = current_user.account.listings.create listings_params
    if @listing.save
      redirect_to listings_path, flash: { notice: 'New Listing Created'}
    else
      render :new
    end
  end

  def show
    @listing = Listing.find params[:id]
    @hash = Gmaps4rails.build_markers(@listing) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
      marker.infowindow listing.title
      marker.json({ title: listing.description })
      marker.picture({
        "url" => "/mapicons/house.png",
        "width" => 32,
        "height" => 32
        })
    end
  end

  def edit
    @listing = Listing.find params[:id]
  end

  def update
    @listing = Listing.find params[:id]
    @listing.update_attributes listings_params
    if @listing.save
      redirect_to :back, flash: { notice: 'Listing successfully updated'}
    else
      redirect_to :back, flash: { notice: 'Unable to update listing'}
    end
  end

  def destroy
    @listing = Listing.find params[:id]
    if @listing.destroy
      redirect_to :back, flash: { notice: 'Listing successfully deleted'}
    else
      redirect_to :back, flash: { notice: 'Unable to delete listing'}
    end
  end

  def listings_params
    params.require(:listing).permit! if params[:listing]
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.haml
.fieldset
  = simple_form_for @listing, html: { class: 'form-horizontal' } do |f|
    .col-sm-4
      .form-group
        = f.input :listing_number
      .form-group
        = f.input :title
      .form-group
        = f.input :price, as: :decimal, label: 'Asking price'
      .form-group
        = f.input :house_number
      .form-group
        = f.input :street_name
      .form-group
        = f.input :city_name, label: 'City'
      .form-group
        = f.input :state, collection: (us_states)
      .form-group
        = f.input :zipcode
      .form-group
        = f.input :listing_owner, collection: (@account_contacts), label: "Owners name"
      .form-group
        = f.input :creating_agent, collection: (@account_users), label: 'Creating agent'
    .col-sm-4.col-sm-offset-1
      .form-group
        = f.input :beds
      .form-group
        = f.input :baths
      .form-group
        = f.input :house_size
      .form-group
        = f.input :property_type
      .form-group
        = f.input :stories, as: :integer
      .form-group
        = f.input :lot_size
      .form-group
        = f.input :year_built
      .form-group
        = f.input :garage
    .row
      .col-sm-8
        = f.input :description, as: :bootsy
    .row
      .col-sm-8
        = f.submit class: 'btn btn-primary'
        = link_to 'Cancel', listings_path, class: "btn btn-danger"

app/views/listings/edit.html.haml
%br
.row
  .col-sm-10
    .box.bordered-box.blue-border
      .box-header.blue-background
        .title
          Edit Listing
        = link_to 'View Listing', listing_path(@listing), class: 'btn btn-primary', id: 'view-listing-button'
      .box-content.box-double-padding
        .form
          = render partial: 'form'

app/views/listings/index.html.haml
= javascript_include_tag  "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry"
= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"
= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js"

- content_for :subnav do
  .row
    .col-sm-12
      / .col-md-6
      / = link_to 'Clear Search', listings_path, class: 'btn btn-default'
      / = link_to 'Toggle Map', "#", class: 'btn btn-default', id: 'display-map'
      / = link_to 'New Listing', new_listing_path, class: 'btn btn-default'

      / #search-listings
      /   %form.form-search{:url => "/listings", :method => "GET"}
      /     %input.input-medium.search-query{:name => "query", :type => "text"}
      /       %button.btn.btn-default{:type => "submit"} Search Listings

.row
  .col-sm-10.col-sm-offset-1
    #listings-map

.row
  .col-sm-10
    .box.box-content.box-no-padding
      .responsive-table
        .scrollable-area
          %table#datatable.table.table-bordered
            %thead
              %tr
                %th
                  Title
                %th
                  Bedrooms
                %th
                  Bathrooms
                %th
                  Price
                %th
                  Address
                %th
                  City
                %th
                  State
                %th
                  Zip
                %th
                  Actions

            %tbody
              - if @listings.present?
                - @listings.each do |f|
                  %tr
                    %td
                      = link_to f.title, f
                    %td
                      = f.beds
                    %td
                      =f.baths
                    %td
                      = number_to_currency(f.price)
                    %td
                      = f.street_address
                    %td
                      =f.city_name
                    %td
                      =f.state
                    %td
                      =f.zipcode
                    %td
                      = link_to listing_path(f) do
                        %i.fa.fa-info-circle
                      = link_to edit_listing_path(f), id: 'edit' do
                        %i.fa.fa-edit
                      = link_to listing_path(f), data: {confirm: 'Are you sure that you want to delete this listing?'}, method: :delete, id: 'delete' do
                        %i.fa.fa-trash-o

:javascript
  buildMap(#{raw @hash.to_json});

app/views/listings/new.html.haml
- content_for :subnav do
  .row
    .col-sm-12
      %h1
        New Listing

.row
  .col-sm-12
    .box
      .form
        = render partial: 'form'

app/views/listings/show.html.haml
= javascript_include_tag  "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry"
= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"
= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js"

%br
.row
  .col-sm-12
    .content{style: 'overflow:auto;'}
      .title
        View Listing
      .row
        .col-sm-2

          %p Listing number
          %p Title:
          %p Price:
          %p Address:
          %p City:
          %p State:
          %p Zip:
          %p Bedrooms:
          %p Bathrooms
          %p House size:
          %p Property type:
          %p Stories:
          %p Lot size:
          %p Year built
          %p Garage:
          %p Listing owner:
          %p Listing agent:
          %p Description:

        .col-sm-4
          %p
            = @listing.listing_number
          %p
            = @listing.title
          %p
            = number_to_currency @listing.price
          %p
            = @listing.street_address
          %p
            = @listing.city_name
          %p
            = @listing.state
          %p
            = @listing.zipcode
          %p
            = @listing.beds.present? ? @listing.beds : "N/A"
          %p
            = @listing.baths.present? ? @listing.baths : "N/A"
          %p
            = @listing.house_size.present? ? @listing.house_size : "N/A"
          %p
            = @listing.property_type.present? ? @listing.property_type : "N/A"
          %p
            = @listing.stories.present? ? @listing.stories : "N/A"
          %p
            = @listing.lot_size.present? ? @listing.lot_size : "N/A"
          %p
            = @listing.year_built.present? ? @listing.year_built : "N/A"
          %p
            = @listing.garage.present? ? @listing.garage : "N/A"
          %p
            = @listing.listing_owner
          %p
            = @listing.creating_agent
          %p
            = raw @listing.description
        .col-sm-6
          = link_to 'Edit Listing', edit_listing_path(@listing), class: 'btn btn-primary', id: 'edit-listing-button'
          #single-listing-map

:javascript
  buildShowMap(#{raw @hash.to_json});