config/routes.rb
AgentSignals::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
    get "logout",     to: "devise/sessions#destroy",    as: "logout"
    get "login",      to: "devise/sessions#new",        as: "login"
    get "signup",     to: "devise/registrations#new",   as: "signup"
  end

  get 'searches/show'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get "contact_form/new"
  get "contact_form/create"

  resources :users
  get "dashboard",  to: "users#dashboard"

  get "web_to_lead" => "leads#new_web_lead", as: "web_to_lead"
  put "create_web_lead" => "leads#create_web_lead", as: "create_web_lead"
  put "generate" => "leads#external_form"

  get 'contact_us' => 'contact_forms#new', as: 'contact_us'
  get 'pricing' => 'pages#pricing', as: 'pricing'

  # Wizards
  resources :after_signup

  resources :agents
  resources :listings
  resources :offers
  resources :opportunities
  resources :tasks
  resources :calendar
  resources :events do
    get :new_task,          on: :collection
    get :new_appointment,   on: :collection
    get :new_showing,       on: :collection
  end

  resources :users do 
    get :settings, on: :member
  end
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      post :convert_to_client
      get :convert
    end
  end

  resources :clients

  namespace :admin do
    resources :users
    resources :organizations
  end

  resources :contact_forms

  resources :contacts
  resources :accounts do
    member do
      get :settings
      post :add_user
    end
  end


end

app/models/lead.rb
class Lead < Contact
  acts_as_taggable # Alias for acts_as_taggable_on :tags

  belongs_to :user
  belongs_to :account


  accepts_nested_attributes_for :notes, allow_destroy: true
  validates_presence_of :lead_owner

  STATUS      = [['New', 'new'], ['Contacted', 'contacted'], ['Qualified', 'qualified'], ['Disqualified', 'disqualified']]
  SOURCES     = [['Web Lead', 'web'], ['Phone', 'phone'], ['Referral', 'referral'], ['Conference', 'conference']]
  INTERESTS   = [['Buyer', 'buyer'], ['Seller', 'seller'], ['Renter', 'renter'], ['Past Client', 'past_client']]


  class << self
    def status
      STATUS
    end

    def sources
      SOURCES
    end

    def interests
      INTERESTS
    end
  end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_filter :authenticate_user!, :except => ['external_form']

  def new
    @lead           = current_user.account.leads.new
    @lead_owner     = current_user.account.users.map(&:email)
    @lead_status    = Lead.status
    @lead_sources   = Lead.sources
    @lead_interests = Lead.interests
  end

  def create
    @lead = current_user.account.leads.new(leads_params)
    @lead.user = User.where(email: @lead.lead_owner).first
    if @lead.save
      current_user.account.leads << @lead
      LeadMailer.notify_new_lead(@lead.lead_owner, @lead).deliver
      redirect_to lead_path @lead, flash[:notice] = 'New Lead Created'
    else
      render :new
    end
  end

  def index
    @leads = current_user.account.leads
  end

  def show
    @lead = Lead.find params[:id]
    @users = current_user.account.users
    @lead_status    = Lead.status
    @lead_sources   = Lead.sources
    @lead_interests = Lead.interests
  end

  def convert_to_client
    @lead = Lead.find params[:id]
    if @lead.update_attributes type: "Client"
      redirect_to :back, notice: "Congratulations! Lead has been converted to a Client."
    else
      redirect_to :back
      flash[:error] = "Something went wrong."
    end
  end

  def edit
    @lead_status    = Lead.status
    @lead_sources   = Lead.sources
    @lead_interests = Lead.interests
  end

  def update
    @lead = current_user.account.leads.find params[:id]
    if params[:commit] == 'Convert'
      convert_lead
    else
      if @lead.update_attributes(leads_params)
        LeadMailer.notify_updated_lead(@lead.lead_owner, @lead).deliver
        redirect_to lead_path @lead, flash[:notice] = 'Lead Updated'
      else
        render :edit
      end
    end
  end

  def destroy
    @lead = Lead.find params[:id]

    if @lead.destroy
      flash[:notice] = 'Lead Deleted'
      redirect_to :back
    else
      flash[:error] = 'Lead could not be deleted'
      redirect_to :back
    end
  end

  def convert
    @lead               = current_user.account.leads.find params[:id]
    @opportunity_owner  = current_user.account.users.map(&:email)
  end

  def convert_lead
    @lead = current_user.account.leads.find params[:id]
    @lead.update_attributes(leads_params)
    @account = current_user.account
    @contacts = current_user.account.contacts.to_a.map(&:email)
    unless @contacts.include? @lead.email
      @contact = current_user.account.contacts.create params['lead']
    end
    @opportunities = current_user.account.opportunities.to_a.map(&:opportunity_name)
    unless @opportunities.include? @lead.opportunity_name
      @opportunity = current_user.account.opportunities.create(opportunity_name: @lead.opportunity_name, owner: @lead.opportunity_owner)
    end
    flash[:notice] = 'Lead has been converted'
    redirect_to opportunity_path(@opportunity)
  end

  def new_web_lead
    leads = Lead.new
    minus_lead = ["_type","_id","created_at", "updated_at", "lead_source", "lead_status","lead_owner", "account_name","opportunity_name","opportunity_owner","assigned_to_id", "interested_in"]
    lead = leads.attribute_names.to_a
    @lead = lead-minus_lead
  end

  def create_web_lead
    @in_lead = []
    default_url = "http://demo.railscrm.com" #CHANGE THIS TO A VALID URL
    fields = ["first_name","last_name", "email", "company", "phone", "address", "city", "state", "zip", "comments"]
    fields.each do |field|
      if params["#{field}"].present?
        @in_lead << field
      end
    end
    @value=""
    @required="required"
    @lead_owner = encrypt(current_user.email)
    @redirect_url = params[:redirect_url].empty? ? default_url : params[:redirect_url]
    render "web_form"
  end

  def external_form
    email = decrypt(params[:lead_owner])
    user = User.where(:email =>email).first
    requestor = "#{request.protocol}#{request.fullpath}"
    if user.nil?
      redirect_to requestor
    else
      redirect_url = params[:redirect_url]
      leads = params[:params].split(" ")
      @lead = Lead.new
      leads.each do |lead|
        @lead.update_attribute("#{lead}", params["#{lead}"])
      end
      @lead.update_attributes(:lead_owner => email,:lead_source => requestor)
      if @lead.save!
        LeadMailer.notify_web_form_lead(@lead.lead_owner, @lead).deliver
        redirect_to redirect_url
      end
    end
  end

  def leads_params
    params.require(:lead).permit! if params[:lead]
  end

  private
    def encrypt(data)
      return encrypted_data = KEY.enc(data)
    end

    def decrypt(encrypted_data)
      return data = KEY.dec(encrypted_data)
    end

end

app/views/leads/_actions.html.haml
poop

app/views/leads/_form.html.haml
.fieldset
  = simple_form_for @lead, :html => { :class => 'form-horizontal' }  do |f|
    .col-sm-4
      .form-group
        = f.input :first_name
      .form-group
        = f.input :last_name
      .form-group
        = f.input :email, as: :email
      .form-group
        = f.input :phone
      .form-group
        = f.input :comments, as: :text, :input_html => {rows: 5}
    .col-sm-4.col-sm-offset-1
      .form-group
        = f.input :assignee_id, label: "Lead Assigned To", collection: @users.collect {|user| [user.full_name, user.id] }
      .form-group
        = f.input :lead_type, collection:(@lead_interests)
      .form-group
        = f.input :lead_status, collection:(@lead_status)
      .form-group
        = f.input :lead_source, collection:(@lead_sources)

    .row
      .col-sm-10
        %h4 Address Info
        .col-sm-4
          .form-group
            = f.input :address
          .form-group
            = f.input :city
        .col-sm-4.col-sm-offset-1
          .form-group
            = f.input :state
          .form-group
            = f.input :zip

    .row
      = f.submit class: 'btn btn-primary'
      = link_to 'Cancel', leads_path, class: "btn btn-danger"

app/views/leads/convert.html.haml
.form
  %h2
    Convert Lead
  %br
  .form-horizontal
    = simple_form_for @lead, :html => { :class => 'form-horizontal' }  do |f|
      %fieldset
        %legend Lead Info
        .row
          .left-column
            = f.input :first_name
            = f.input :last_name
            = f.input :email, as: :email
            = f.input :phone
          .right-column
            = f.input :opportunity_name
            = f.input :opportunity_owner, collection:(@opportunity_owner)

        .row.pull-right{style: 'margin-right:20px;margin-bottom:20px'}
          = f.submit 'Convert', class: 'btn btn-primary'

app/views/leads/convert_form.html.haml
=javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
=javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"
=form_tag("http://demo.railscrm.com/generate",name: "web_form", id: "web_form", class: "web_form") do
  =hidden_field_tag :lead_owner, @lead_owner
  =hidden_field_tag :params, @in_lead
  =hidden_field_tag :redirect_url, @redirect_url
  -for a in 0..@in_lead.size-1 do
    =label_tag @in_lead[a]
    -if @in_lead[a] == 'email'
      =text_field_tag @in_lead[a], @value, class: "required email"
    -else
      =text_field_tag @in_lead[a], @value, class: "required"
    %br

  =submit_tag "Submit", class: 'btn btn-primary'
%script 
  $("#web_form").validate();

app/views/leads/index.html.haml
- content_for :subnav do
  .row
    .col-md-12

.row
  .col-sm-12
    .box.box-content.box-no-padding
      .responsive-table
        .scrollable-area
          %table#datatable.table.table-bordered
            %thead
              %tr
                %th
                  Name
                %th
                  Company
                %th
                  Phone
                %th
                  Status
                %th
                  Assigned to
                %th
                  Created Date
                %th
                  Actions
            %tbody
              - @leads.each do |lead|
                %tr
                  %td
                    = lead.full_name
                  %td
                    = lead.company
                  %td
                    = lead.phone
                  %td
                    = lead.lead_status.to_s.capitalize
                  %td
                    = lead.lead_owner
                  %td
                    = lead.created_at.to_date
                  %td
                    = link_to lead_path(lead), id: 'edit' do
                      %i.fa.fa-edit
                    = link_to lead_path(lead), data: {confirm: 'Are you sure that you want to delete this lead?'}, method: :delete, id: 'delete' do
                      %i.fa.fa-trash-o

app/views/leads/new.html.haml
- content_for :subnav do
  .row
    .col-sm-12
      %h1 New Lead

.row
  .col-sm-12
    .box
      .form
        = render partial: 'form'

app/views/leads/new_web_lead.html.haml
- content_for :subnav do
  .row
    .col-sm-12
      %h1 New Web-to-Lead Form


.row
  .col-sm-12
    .box
      .box-content.box-double-padding
        %p
          The Web-to-Lead form generator is used to create the form code that can be used on your website as a way to create leads from visitors.
        %p
          The Redirect URL is the page that you want to redirect to after the form is submitted. Select the fields that you want your form to have and click "Create Form".
        %br
        .form
          = form_tag create_web_lead_path, :class => 'simple_form', method: :put do
            %fieldset
              .row
                .form-group
                  Redirect URL
                  = text_field_tag :redirect_url

              .row
                .col-sm-4
                  .form-group
                    -for a in 0..@lead.size/2-1 do
                      =check_box_tag @lead[a]
                      =@lead[a]
                      %br

                .col-sm-4.col-sm-offset-1
                  .form-group
                    =hidden_field_tag :lead,@lead
                    -for b in @lead.size/2..@lead.size-1 do
                      =check_box_tag @lead[b]
                      =@lead[b]
                      %br

              .row
                .col-sm-8
                  = submit_tag "Create Form", class: 'btn btn-primary'
                  = link_to 'Cancel', leads_path, class: "btn btn-danger"

app/views/leads/show.html.haml
.row
  .col-sm-10
    %h1 View Lead

.row
  .col-sm-10
    .box

      .pull-right{style: 'margin-top:-10px'}
        = link_to 'Convert Lead', convert_to_client_lead_path(@lead), method: :post, class: 'btn btn-primary'
      .form
        = render partial: 'form'

        %fieldset
          %legend{style: 'width:97%'}
            Lead Activities
          .activities-section
            %h4 Recent Activity for #{@lead.full_name}:
            %p
              %table.table.table-striped
                %thead
                  %tr
                    %th
                      Note
                    %th
                      Type
                    %th
                      Due Date
                    %th
                      Actions
                %tbody
                  - if @lead.notes
                    - @lead.notes.each do |note|
                      %tr
                        %td
                          = note.content
                        %td
                          = note.note_type
                        %td
                          = note.due_date
                        %td
                          / = link_to '', edit_lead_note_path(@lead, note), class: 'icon-edit', id: 'edit'
                          = link_to '', lead_note_path(@lead, note), method: 'delete', class: 'icon-trash', data: { confirm: 'Are you sure that you want to delete this note?'}, id: 'delete'

            %p
            - if @note
              = render 'notes/edit'

            %hr
            %h3 Create a new note:
            %p
              = simple_form_for [@lead, Note.new] do |n|
                = n.input :content, as: :text, input_html: {rows: 5, class: "field span7"}
                = n.input :note_type, collection:[['Call Back', 'call'],['Email', 'email'], ['Follow Up', 'follow_up']]
                = n.input :due_date, as: :string, input_html: { :class => 'jquery-ui-date'}
                = n.submit 'Add new Note', class: 'btn btn-primary'

app/views/leads/web_form.html.haml
%section#content{style: "margin-left:10px"}
  .container
    #content-wrapper.row
      .col-xs-10
        .row
          .col-sm-10
            .page-header
              %h1.pull-left
                %i.icon-user
                %span New Web Form
            %p
              Copy the form below and use it anywhere in your website.
            %p
              =text_area_tag "web_form",(render file: 'leads/convert_form'), readonly: true, style: "width:850px; height:400px"
            %br
              = link_to "Back", dashboard_path, class: 'btn btn-primary'