config/routes.rb
AgentSignals::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
    get "logout",     to: "devise/sessions#destroy",    as: "logout"
    get "login",      to: "devise/sessions#new",        as: "login"
    get "signup",     to: "devise/registrations#new",   as: "signup"
  end

  get 'searches/show'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get "contact_form/new"
  get "contact_form/create"

  resources :users
  get "dashboard",  to: "users#dashboard"

  get "web_to_lead" => "leads#new_web_lead", as: "web_to_lead"
  put "create_web_lead" => "leads#create_web_lead", as: "create_web_lead"
  put "generate" => "leads#external_form"

  get 'contact_us' => 'contact_forms#new', as: 'contact_us'
  get 'pricing' => 'pages#pricing', as: 'pricing'

  # Wizards
  resources :after_signup

  resources :agents
  resources :listings
  resources :offers
  resources :opportunities
  resources :tasks
  resources :calendar
  resources :events do
    get :new_task,          on: :collection
    get :new_appointment,   on: :collection
    get :new_showing,       on: :collection
  end

  resources :users do 
    get :settings, on: :member
  end
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      post :convert_to_client
      get :convert
    end
  end

  resources :clients

  namespace :admin do
    resources :users
    resources :organizations
  end

  resources :contact_forms

  resources :contacts
  resources :accounts do
    member do
      get :settings
      post :add_user
    end
  end


end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :contact

  validates :due_date, presence: true

  validate :end_date_is_after_start_date, if: :end_date?

  default_scope -> { order('due_date DESC') }

  def end_date?
    self.ends.present?
  end

  private

  def end_date_is_after_start_date
    errors.add(:ends, "End date must be after start date") if self.due_date > self.ends
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    start_range = Time.at params[:start].to_i
    end_range = Time.at params[:end].to_i
    @user = current_user
    @events = current_user.events
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @start = params[:start]
    @end = params[:end]
    @user = current_user
    @task = Task.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new_task
    @start = params[:start] ? DateTime.parse(params[:start]).strftime("%b %d, %Y %I:%M %P") : nil
    @end = params[:end] ? DateTime.parse(params[:end]).strftime("%b %d, %Y %I:%M %P") : nil
    @task = Task.new
  end

  def new_appointment
    @start = params[:start] ? DateTime.parse(params[:start]).strftime("%b %d, %Y %I:%M %P") : nil
    @end = params[:end] ? DateTime.parse(params[:end]).strftime("%b %d, %Y %I:%M %P") : nil
    @appointment = Appointment.new
  end

  def new_showing
    @start = params[:start] ? DateTime.parse(params[:start]).strftime("%b %d, %Y %I:%M %P") : nil
    @end = params[:end] ? DateTime.parse(params[:end]).strftime("%b %d, %Y %I:%M %P") : nil
    @showing = Showing.new
    @clients = current_user.clients
  end

  def show
    @event = Event.find params[:id]
  end

  def create
    @clients = current_user.clients
    @event = if params[:task]
      current_user.tasks.build task_params
    elsif params[:appointment]
      current_user.appointments.build appointment_params
    elsif params[:showing]
      current_user.showings.build showing_params
    end
    @task, @appointment, @showing = @event, @event, @event
    respond_to do |format|
      if @event.save
        format.html {redirect_to calendar_index_path, notice: "Event added successfully"}
        format.js
      else
        format.html do 
          if @event.type == "Task"
            render :new_task
          elsif @event.type == "Appointment"
            render :new_appointment
          elsif @event.type == "Showing"
            render :new_showing
          end
        end
        format.js
      end
    end
  end

  def edit
    @clients = current_user.clients
    @event = Event.find params[:id]
  end

  def update
    @clients = current_user.clients
    @event = Event.find params[:id]
    parameters = if params[:task]
      task_params
    elsif params[:appointment]
      appointment_params
    elsif params[:showing]
      showing_params
    elsif params[:event]
      event_params
    end
    respond_to do |format|
      if @event.update parameters
        format.html {redirect_to calendar_index_path, notice: "Event has been updated successfully"}
        format.js
      else
        format.html {render :edit}
        format.js
      end
    end
  end

  def destroy
    @event = Event.find params[:id]
    @event.destroy
    respond_to do |format|
      format.html {redirect_to calendar_index_path, notice: "Event has been deleted successfully"}
      format.js
    end
  end

  private

  def event_params
    params.require(:event).permit!
  end

  def task_params
    params.require(:task).permit!
  end

  def appointment_params
    params.require(:appointment).permit!
  end

  def showing_params
    params.require(:showing).permit!
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def event_color_options
    [
      ['Blue', '#428bca'], 
      ['Green', '#5cb85c'], 
      ['Orange', '#f0ad4e'],
      ['Red', '#d9534f']
    ]
  end
end

app/views/events/_appointment_form.html.haml
- ajax ||= false

= simple_form_for @appointment, url: params[:action] == "edit" ? event_path(@appointment) : events_path, method: params[:action] == "edit" ? :put : :post, remote: ajax do |f|
  .clearfix
    = f.input :name
  .row.clearfix
    .col-md-6.col-sm-12
      = f.input :due_date, label: "Starts", as: :string, input_html: { autocomplete: "off", class: 'datetime-picker', value: f.object.due_date.present? ? localize(f.object.due_date, format: "%b %d, %Y %I:%M %P") : @start }
    .col-md-6.col-sm-12
      = f.input :ends, as: :string, input_html: { autocomplete: "off", class: 'datetime-picker', value: f.object.ends.present? ? localize(f.object.ends, format: "%b %d, %Y %I:%M %P") : @end }
  .clearfix
    = f.input :all_day
  .clearfix
    = f.input :notes, input_html: { rows: 5 }
  .clearfix
    = f.submit class: 'btn btn-primary'

app/views/events/_show.html.haml
- ajax ||= false
.row.clearfix
  .col-md-2
    %strong #{@event.type}: 
  .col-md-10
    = @event.name

.row.clearfix 
  .col-md-2
    - if @event.type == "Task"
      %strong Due Date: 
    - else
      %strong Starts: 
  .col-md-10
    = @event.due_date.strftime("%B %d, %Y")

- if @event.ends.present?
  .row.clearfix
    .col-md-2
      %strong Ends: 
    .col-md-10
      = @event.ends.strftime("%B %d, %Y")

.row.clearfix
  .col-md-2
    Assigned To: 
  .col-md-10
    = @event.assigned_to

.row.clearfix
  .col-sm-12
    %strong Notes:
    %p= @event.notes 

- if @event.type == "Showing"
  .row.clearfix
    .col-sm-12
      %h2 Listings to Show

.row
  .col-sm-12
    = link_to "Edit", edit_event_path(@event), remote: ajax, class: 'btn btn-primary'
    = link_to "Delete", event_path(@event), data: {confirm: "Are you sure?"}, method: :delete, remote: ajax, class: 'btn btn-danger'

app/views/events/_showing_form.html.haml
- ajax ||= false

= simple_form_for @showing, url: params[:action] == "edit" ? event_path(@showing) : events_path, method: params[:action] == "edit" ? :put : :post, remote: ajax do |f|
  .clearfix
    = f.input :contact_id, collection: @clients.collect { |client| [client.full_name, client.id] }
  .row.clearfix
    .col-md-6
      = f.input :due_date, label: "Starts", as: :string, input_html: { autocomplete: "off", class: 'datetime-picker', value: f.object.due_date.present? ? localize(f.object.due_date, format: "%b %d, %Y %I:%M %P") : @start }
    .col-md-6
      = f.input :ends, as: :string, input_html: { autocomplete: "off", class: 'datetime-picker', value: f.object.ends.present? ? localize(f.object.ends, format: "%b %d, %Y %I:%M %P") : @end }
  .row.clearfix
    .col-sm-12
      = f.input :all_day
  .row.clearfix
    .col-sm-12
      = f.input :notes, input_html: { rows: 5 }
  .row.clearfix
    .col-sm-12
      = f.submit class: 'btn btn-primary'

app/views/events/_task_form.html.haml
- ajax ||= false

= simple_form_for @task, url: params[:action] == "edit" ? event_path(@task) : events_path, method: params[:action] == "edit" ? :put : :post, remote: ajax do |f|
  .clearfix
    = f.input :name
  .clearfix
    = f.input :due_date, as: :string, input_html: { autocomplete: "off", class: 'datetime-picker', value: f.object.due_date.present? ? localize(f.object.due_date, format: "%b %d, %Y %I:%M %P") : @start  }
  .clearfix
    = f.input :notes, input_html: { rows: 5 }
  .clearfix
    = f.submit class: 'btn btn-primary'

    

app/views/events/create.js.erb
<% if @event.errors.present? %>
  
  <% if @event.type == "Task" %>
    $('.modal-body p').html("<%= j render partial: 'events/task_form', locals: {ajax: true} %>");
  <% elsif @event.type == "Appointment" %>
    $('.modal-body p').html("<%= j render partial: 'events/appointment_form', locals: {ajax: true} %>");
  <% elsif @event.type == "Showing" %>
    $('.modal-body p').html("<%= j render partial: 'events/showing_form', locals: {ajax: true} %>");
  <% end %>

  $('.datetime-picker').datetimepicker({
    format: 'M d, Y h:i a', 
    step: 30
  });

<% else %>

  $('#event-modal').modal('hide');
  $('#full-calendar').fullCalendar('refetchEvents');

<% end %>

app/views/events/destroy.js.erb
$('#event-modal').modal('hide');
$('#full-calendar').fullCalendar( 'refetchEvents' )

app/views/events/edit.html.haml
.row
  .col-sm-12
    %h1 Edit #{@event.type}

.row
  .col-sm-12
    .box
      - if @event.type == "Task"
        - @task = @event
        = render "task_form"
      - elsif @event.type == "Appointment"
        - @appointment = @event
        = render "appointment_form"
      - elsif @event.type == "Showing"
        - @showing = @event
        = render "showing_form"

app/views/events/edit.js.erb
$('.modal-title').html("Edit <%= @event.type %>");

<% if @event.type == "Task" %>
  <% @task = @event %>
  $('.modal-body p').html("<%= j render partial: 'events/task_form', locals: {ajax: true} %>");

<% elsif @event.type == "Appointment" %>
  <% @appointment = @event %>
  $('.modal-body p').html("<%= j render partial: 'events/appointment_form', locals: {ajax: true} %>");

<% elsif @event.type == "Showing" %>
  <% @showing = @event %>
  $('.modal-body p').html("<%= j render partial: 'events/showing_form', locals: {ajax: true} %>");

<% end %>

$('.datetime-picker').datetimepicker({
  format: 'M d, Y h:i a', 
  step: 30
});

app/views/events/new.js.erb
$('#event-modal').modal('show');
$('.modal-title').html("Select Type of Event to Create");
$('.modal-body p').html("<%= j render partial: 'events/new_event', locals: {ajax: true} %>");

$('.datetime-picker').datetimepicker

app/views/events/new_appointment.html.haml
.row
  .col-sm-12
    %h1 New Appointment

.row
  .col-sm-12
    .box
      = render 'appointment_form'

app/views/events/new_showing.html.haml
.row
  .col-sm-12
    %h1 New Showing

.row
  .col-sm-12
    .box
      = render 'showing_form'

app/views/events/new_task.html.haml
.row
  .col-sm-12
    %h1 New Task

.row
  .col-sm-12
    .box
      = render 'task_form'

app/views/events/new_task.js.erb
$('.modal-footer').remove();
$('.modal-title').html("New Task");
$('.modal-body p').html("<%= j render partial: 'events/task_form', locals: {ajax: true} %>");
$('.datetime-picker').datetimepicker({
  format: 'M d, Y h:i a', 
  step: 30
});

app/views/events/update.js.erb
<% if @event.errors.present? %>
  
  <% if @event.type == "Task" %>
    <% @task = @event %>
    $('.modal-body p').html("<%= j render partial: 'events/task_form', locals: {ajax: true} %>");
  <% elsif @event.type == "Appointment" %>
    <% @appointment = @event %>
    $('.modal-body p').html("<%= j render partial: 'events/appointment_form', locals: {ajax: true} %>");
  <% elsif @event.type == "Showing" %>
    <% @showing = @event %>
    $('.modal-body p').html("<%= j render partial: 'events/showing_form', locals: {ajax: true} %>");
  <% end %>

  $('.datetime-picker').datetimepicker({
    format: 'M d, Y h:i a', 
    step: 30
  });

<% else %>

  $('#event-modal').modal('hide');
  $('#full-calendar').fullCalendar('refetchEvents');

<% end %>