config/routes.rb
AgentSignals::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
    get "logout",     to: "devise/sessions#destroy",    as: "logout"
    get "login",      to: "devise/sessions#new",        as: "login"
    get "signup",     to: "devise/registrations#new",   as: "signup"
  end

  get 'searches/show'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get "contact_form/new"
  get "contact_form/create"

  resources :users
  get "dashboard",  to: "users#dashboard"

  get "web_to_lead" => "leads#new_web_lead", as: "web_to_lead"
  put "create_web_lead" => "leads#create_web_lead", as: "create_web_lead"
  put "generate" => "leads#external_form"

  get 'contact_us' => 'contact_forms#new', as: 'contact_us'
  get 'pricing' => 'pages#pricing', as: 'pricing'

  # Wizards
  resources :after_signup

  resources :agents
  resources :listings
  resources :offers
  resources :opportunities
  resources :tasks
  resources :calendar
  resources :events do
    get :new_task,          on: :collection
    get :new_appointment,   on: :collection
    get :new_showing,       on: :collection
  end

  resources :users do 
    get :settings, on: :member
  end
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      post :convert_to_client
      get :convert
    end
  end

  resources :clients

  namespace :admin do
    resources :users
    resources :organizations
  end

  resources :contact_forms

  resources :contacts
  resources :accounts do
    member do
      get :settings
      post :add_user
    end
  end


end

app/models/account.rb
class Account < ActiveRecord::Base

  validates_presence_of :name, :phone, :subscription_plan, :max_users
  validates :name, uniqueness: true

  has_many :leads
  has_many :agents
  has_many :users
  has_many :contacts
  has_many :opportunities
  has_many :listings

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @account = Account.new
  end

  def create
    @account = Account.create(account_params)
    if @account.save
      @account.users << current_user
      flash[:notice] = 'Account successfully created'
      redirect_to :dashboard
    else
      flash[:error] = 'Unable to create account'
      redirect_to :back
    end
  end

  def update
    @account = Account.find params[:id]
    if @account.update_attributes(account_params)
      flash[:notice] = 'Successfully updated your account'
      redirect_to :back
    else
      flash[:error] = 'Unable to update your account'
      redirect_to :back
    end
  end

  def add_user
    @account = Account.find params[:id]
    if @account.users.create(user_params)
      flash[:notice] = 'User successfully added'
      redirect_to :back
    else
      flash[:error] = 'Unable to add new user'
      redirect_to :back
    end
  end

  def settings
    @user = current_user
    @users = current_user.account.users
    @account = Account.find params[:id]
  end

  def account_params
    params.require(:account).permit! if params[:account]
  end

  def user_params
    params.require(:user).permit! if params[:user]
  end
end

app/views/accounts/_add_user.html.haml
.account-new-user-section
  = simple_form_for @account.users.new, url: add_user_account_path(@account) do |f|
    = f.error_notification
    .col-sm-4
      .form-group
        .controls
          = f.input :first_name, required: true
      .form-group
        .controls
          = f.input :last_name, required: true
      .form-group
        .controls
          = f.input :email, required: true
    .col-sm-4.col-sm-offset-1
      .form-group
        .controls
          = f.input :password, required: true
      .form-group
        .controls
          = f.input :password_confirmation, required: true
      .form-group
        .controls{style: 'margin-top:35px;margin-bottom:40px;'}
          = f.submit 'Add User', class: 'btn btn-primary'

app/views/accounts/_form.html.haml
.fieldset
  = simple_form_for @account, :html => { :class => 'form-horizontal' }  do |f|
    .col-sm-4
      .form-group
        = f.input :subscription_plan, collection:([['Basic', '1']]), selected: @account.subscription_plan, label: 'Plan type', required: true
      .form-group
        = f.input :name, label: 'Account name'
      .form-group
        = f.input :phone
    .col-sm-4.col-sm-offset-1
      .form-group
        = f.input :address
      .form-group
        = f.input :city
      .form-group
        = f.input :state, collection: (us_states)
      .form-group
        = f.input :zip

    .row
      .col-sm-8
        = f.submit class: 'btn btn-primary'
        = link_to 'Cancel', accounts_path, class: "btn btn-danger"

app/views/accounts/_users.html.haml
.row
  .col-sm-12
    .box.box-content.box-no-padding
      .responsive-table
        .scrollable-area
          %table#datatable.table.table-bordered
            %thead
              %tr
                %th
                  Name
                %th
                  Email
                %th
                  Phone

            %tbody
              - @users.each do |user|
                %tr
                  %td
                    = user.full_name
                  %td
                    = user.email
                  %td
                    = user.phone

app/views/accounts/new.html.haml
%br
.row
  .col-sm-10
    .box.bordered-box.blue-border
      .box-header.blue-background
        .title
          Create New Account
      .box-content.box-double-padding
        .form
          = render partial: 'form'

app/views/accounts/settings.html.haml
.row
  .col-sm-10
    %h1= "#{@account.name} Settings"

.row
  .col-sm-10
    .box
      = render partial: 'form'

.row.clearfix
  .col-sm-10
    .box
      %h3 Account Users
      %p
        = link_to 'Add a User', "#", class: 'btn btn-primary', id: 'add-user-to-account'

      .new-user-add-form
        = render 'add_user'

      = render 'users'

app/views/accounts/show.html.haml
%br
.row
  .col-sm-10
    .box.bordered-box.blue-border
      .box-header.blue-background
        .title
          View Account
      .box-content.box-double-padding
        .form
          = render partial: 'form'